before_install:
  - openssl aes-256-cbc -K $encrypted_3c592228dd61_key -iv $encrypted_3c592228dd61_iv -in deploy_static.pem.enc -out deploy_static.pem -d

script:
  - echo "198.211.102.17 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBO+G8ELGG/NTCQ/3H2O7i8POqq9eKkeAnW2emTiEnBEgEFIfc5k/oUUWSFDniqN14tkpkL1t4tTOdaetqhJvxp0=" > ~/.ssh/known_hosts
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_static.pem
  - ssh-add .travis/deploy_static.pem
  - git remote add deploy dokku@198.211.102.17:test.pymedusa.com
  - git push deploy master
